### ISSUE TITLE
Provide version numbers for Python packages

### ISSUE THREAD

**Issue by Solosneros** [deepmind/jax_privacy#2]
Hi,

thanks for providing the source code to your _"Unlocking High-Accuracy Differentially Private Image Classification through Scale"_ paper.
I would be nice if you could provide version numbers for the required packages. So far, I have not been able to run your experiments. It seems that I run into errors with a lot of packages.

Thanks!

**Comment by lberrada** [comment]
In my setup, specifying `jax==0.3.5` (like in [this commit](https://github.com/deepmind/jax_privacy/commit/c10d61bfaa83d6f314e2a59e88c9727e5ac58eff)) within a fresh virtual environment solves the dependency issue.

Please let me know if that does not solve the problem on your end.

**Comment by Solosneros** [comment]
Thanks for the reply! I worked on it in the meantime and debugged the versions and can now at least execute the experiments with `jax==0.3.5` up until another error that might be related to me not having access to TPUs. I will let you know.

**Comment by lberrada** [comment]
Great, resolving the issue since the dependency problem seems solved. Feel free to open a new issue if you encounter another error.
