### ISSUE TITLE
JAX issue: Freezing the python requirements

### ISSUE THREAD

**Issue by RoyRin** [deepmind/jax_privacy#5]
Hi,
I am trying to recreate your results, and there is an issue with JAX using up 100% of a single GPU and freezing on the first training step. 
![image](https://user-images.githubusercontent.com/12860243/187440932-1b9faf76-39a6-401d-9dff-27a5bbeecebb.png)

I think part of the issue is that I am using a different version of JAX than `jax_privacy` expects. Can you please share the exact versions of the python dependencies. Relatedly, it seems like you are using Cuda-11.0 is that correct?

Note: the specific issue arises at this line: https://github.com/deepmind/jax_privacy/blob/main/jax_privacy/src/training/image_classification/updater.py#L213 when it calls `_pmapped_update`, and tries to run `jax.pmap`

**Additional Edits:**
`jax.distributed.initialize` is never called in the codebase, which makes me believe that this code base runs on `Jax <0.3.0`, based off of this changelog here : https://jax.readthedocs.io/en/latest/changelog.html#jax-0-2-25-nov-10-2021 .

**Comment by lberrada** [comment]
Hi, we were able to run this code relatively recently with this requirements file https://github.com/deepmind/jax_privacy/blob/dev/requirements.txt, can you try using that when installing the dependencies? The main change compared to the `main` version of the requirements is that we specify `jax==0.3.5` (otherwise there can be issues with `jaxlib`, that `jax` itself depends on).

That's correct for CUDA, we used CUDA 11.0 and CuDNN 11.1.

**Comment by RoyRin** [comment]
That seems reasonable, I agree.
I was using the config provided, https://github.com/deepmind/jax_privacy/blob/main/experiments/image_classification/configs/cifar10_wrn_16_4_eps1.py which does have
```
batch_size=dict(
                      init_value=4096,
                      per_device_per_step=64,
                      scale_schedule=None,  # example: {'2000': 8, '4000': 16},
                  ),
```
I'll try setting the batch_size to be smaller, and report back.

**Comment by RoyRin** [comment]
I thought this was resolved. But I ran into some more OOM warnings. Now that I'm tracking the jax-privacy code, it looks at each step, the entire dataset is loaded onto the GPU, and utilization hits 100%.

This has now changed in theme from the original issue, so I can open a different issue, if need be. But the direct question is:

Is this warning expected behaviour?:
```
6 dataset_info.py:491] Load dataset info from /h/royrin/tensorflow_datasets/cifar10/3.0.2
I1006 15:49:31.985438 140647251464896 dataset_info.py:550] Field info.splits from disk and from code do not match. Keeping the one from code.
I1006 15:49:31.985566 140647251464896 dataset_info.py:550] Field info.supervised_keys from disk and from code do not match. Keeping the one from code.
I1006 15:49:31.985766 140647251464896 dataset_builder.py:383] Reusing dataset cifar10 (/h/royrin/tensorflow_datasets/cifar10/3.0.2)
I1006 15:49:31.985876 140647251464896 logging_logger.py:44] Constructing tf.data.Dataset cifar10 for split test, from /h/royrin/tensorflow_datasets/cifar10/3.0.2
```

**Comment by lberrada** [comment]
Yes, this is expected, this are standard logs that tensorflow_datasets outputs when loading data. 

Our code should not load the entire dataset on the device at each iteration, unless the batch-size per step per device is specified to do so. At each iteration, we are expecting images of shape `[num_devices, batch_size_per_step_per_device, augmult, *image_dimensions]`.

**Comment by RoyRin** [comment]
Okay thank you,
I will close this issue. I am still getting memory issues some times, but I believe it has to do with the machine, and not the code. 
If it comes up again, I will re-open it.

Thank you for your help!
