### ISSUE TITLE
Share Config for Cifar10 eps != 1

### ISSUE THREAD

**Issue by RoyRin** [deepmind/jax_privacy#6]
Hi,

In the paper https://arxiv.org/pdf/2204.13650.pdf, the following plot is presented:
![image](https://user-images.githubusercontent.com/12860243/196773594-2284fc9d-a5bd-4a62-b255-d7e52f06a2fb.png)
.
However, the configs associated https://github.com/deepmind/jax_privacy/tree/main/experiments/image_classification/configs only have CIFAR10 for `stop_training_at_epsilon = 1`.

I am curious what the config that acheived SOTA looks like. Is the only change the "stop_training_at_epsilon" was set to a larger number, in order to generated the plots in the paper (I presume 8). Or are other values are different, such as `std_relative=10`. 

* If possible, could you share how `std_relative=10.` was selected? 
* and if [this config](https://github.com/deepmind/jax_privacy/blob/main/experiments/image_classification/configs/cifar10_wrn_16_4_eps1.py) was the config used for the SOTA CIFAR-10 results.

**Comment by lberrada** [comment]
Hi, all the hyper-parameters are reported in appendix C.5 of the paper, their values should be straightforward to plug into the existing config files.
